"""
05_final_qa.py

Final QA layer for the W144 Social Media Platform Usage &
User Motivations survey-tabulation project.

Validates:
1. Table-level analytical universes and valid bases.
2. Weighted bases and percentage totals.
3. Effective-base outputs generated by step 04.
4. Small-base / very-small-base flags.
5. Exclusion of N < 100 categories from significance testing.
6. Overall analytical coverage.

Outputs:
- qa/qa_summary.csv
- qa/small_base_qa.csv

Small-base convention:
    N < 30        -> ** VERY SMALL BASE
    30 <= N < 100 -> * SMALL BASE
    N >= 100      -> OK
"""

from pathlib import Path
import re

import numpy as np
import pandas as pd


# ============================================================
# PATHS
# ============================================================

PROJECT_ROOT = Path(__file__).resolve().parents[2]

DATA_PATH = (
    PROJECT_ROOT / "data" / "raw" / "ATP_W144.csv"
)

PLAN_PATH = (
    PROJECT_ROOT / "tabulation" / "tabulation_plan.csv"
)

QA_DIR = PROJECT_ROOT / "qa"
QA_DIR.mkdir(parents=True, exist_ok=True)

EFFECTIVE_BASE_PATH = (
    QA_DIR / "effective_bases.csv"
)

SIGNIFICANCE_PATH = (
    QA_DIR / "significance_test_results.csv"
)

QA_SUMMARY_PATH = (
    QA_DIR / "qa_summary.csv"
)

SMALL_BASE_PATH = (
    QA_DIR / "small_base_qa.csv"
)


# ============================================================
# SETTINGS
# ============================================================

VALID_RESPONSES = [1, 2, 3]

MIN_TEST_BASE = 100
VERY_SMALL_BASE_LIMIT = 30
SMALL_BASE_LIMIT = 100

NUMERIC_TOLERANCE = 1e-8


MEASURE_LABELS = {
    "a": "Get news",
    "b": "Keep up with politics or political issues",
    "c": "Keep up with sports or pop culture",
    "d": "Entertainment",
    "e": "Keep up with friends and family",
    "f": "Connect with others who share your interests",
    "g": "Look at product reviews or recommendations",
}


banner_definitions = {
    "F_AGECAT": {
        1: "18-29",
        2: "30-49",
        3: "50-64",
        4: "65+",
    },
    "F_GENDER": {
        1: "A man",
        2: "A woman",
        3: "In some other way",
    },
    "F_EDUCCAT": {
        1: "College graduate+",
        2: "Some College",
        3: "H.S. graduate or less",
    },
    "F_CREGION": {
        1: "Northeast",
        2: "Midwest",
        3: "South",
        4: "West",
    },
    "F_INC_TIER2": {
        1: "Lower income",
        2: "Middle income",
        3: "Upper income",
    },
}


banner_names = {
    "F_AGECAT": "Age",
    "F_GENDER": "Gender",
    "F_EDUCCAT": "Education",
    "F_CREGION": "Region",
    "F_INC_TIER2": "Income",
}


# ============================================================
# LOAD INPUTS
# ============================================================

df = pd.read_csv(DATA_PATH)
plan = pd.read_csv(PLAN_PATH)

if not EFFECTIVE_BASE_PATH.exists():
    raise FileNotFoundError(
        "qa/effective_bases.csv not found. "
        "Run 04_significance_testing.py first."
    )

if not SIGNIFICANCE_PATH.exists():
    raise FileNotFoundError(
        "qa/significance_test_results.csv not found. "
        "Run 04_significance_testing.py first."
    )

generated_bases = pd.read_csv(
    EFFECTIVE_BASE_PATH
)

sig_results = pd.read_csv(
    SIGNIFICANCE_PATH
)


print("=" * 72)
print("W144 FINAL QA")
print("=" * 72)

print(
    f"\nRaw data: {df.shape[0]:,} rows x "
    f"{df.shape[1]:,} columns"
)

print(f"Tabulation plan: {len(plan)} tables")


# ============================================================
# HELPERS
# ============================================================

def parse_universe(expression):

    pattern = (
        r"^\s*([A-Za-z0-9_]+)"
        r"\s*==\s*(-?\d+(?:\.\d+)?)\s*$"
    )

    match = re.match(
        pattern,
        str(expression)
    )

    if not match:
        raise ValueError(
            "Unsupported universe expression: "
            f"{expression}"
        )

    variable = match.group(1)
    value = float(match.group(2))

    if variable not in df.columns:
        raise KeyError(
            "Universe variable not found: "
            f"{variable}"
        )

    return (
        pd.to_numeric(
            df[variable],
            errors="coerce",
        )
        == value
    )


def get_measure_label(variable):

    match = re.search(
        r"WHY_([a-g])_W144$",
        str(variable),
    )

    if not match:
        raise ValueError(
            "Cannot determine WHY item: "
            f"{variable}"
        )

    return MEASURE_LABELS[
        match.group(1)
    ]


def kish_effective_n(weights):

    weights = pd.to_numeric(
        weights,
        errors="coerce",
    ).dropna()

    if len(weights) == 0:
        return np.nan

    sum_w = weights.sum()
    sum_w2 = (weights ** 2).sum()

    if sum_w2 == 0:
        return np.nan

    return (
        sum_w ** 2
        / sum_w2
    )


def classify_base(n):
    """
    Return presentation value + QA flag.
    """

    n = int(n)

    if n < VERY_SMALL_BASE_LIMIT:
        return (
            f"{n}**",
            "VERY SMALL BASE",
        )

    if n < SMALL_BASE_LIMIT:
        return (
            f"{n}*",
            "SMALL BASE",
        )

    return (
        str(n),
        "OK",
    )


# ============================================================
# BASIC INPUT QA
# ============================================================

assert len(plan) == 28
assert plan["table_id"].nunique() == 28
assert plan["variable"].nunique() == 28

assert len(generated_bases) == 504
assert len(sig_results) == 1596

print("[PASS] Pipeline inputs validated")


# ============================================================
# BUILD TABLE-LEVEL QA SUMMARY
# ============================================================

qa_rows = []

for _, row in plan.iterrows():

    table_id = row["table_id"]
    platform = row["platform"]
    variable = row["variable"]
    weight = row["weight"]
    universe_expression = row["universe"]

    universe_mask = parse_universe(
        universe_expression
    )

    eligible = df.loc[
        universe_mask
    ].copy()

    eligible_n = len(eligible)

    valid_mask = (
        eligible[variable].isin(
            VALID_RESPONSES
        )
        &
        eligible[weight].notna()
    )

    valid = eligible.loc[
        valid_mask
    ].copy()

    valid_n = len(valid)

    special_or_invalid_n = (
        eligible_n - valid_n
    )

    weighted_base = (
        valid[weight].sum()
    )

    percentages = []

    if weighted_base > 0:

        for response in VALID_RESPONSES:

            numerator = valid.loc[
                valid[variable] == response,
                weight,
            ].sum()

            percentages.append(
                numerator
                / weighted_base
                * 100
            )

    percentage_sum = (
        sum(percentages)
        if percentages
        else np.nan
    )

    percentage_qa = (
        "PASS"
        if (
            not pd.isna(percentage_sum)
            and abs(
                percentage_sum - 100
            ) <= 0.2
        )
        else "FAIL"
    )

    qa_rows.append({
        "table_id": table_id,
        "platform": platform,
        "variable": variable,
        "weight": weight,
        "eligible_n": eligible_n,
        "valid_n": valid_n,
        "special_or_invalid_n":
            special_or_invalid_n,
        "weighted_base": weighted_base,
        "percentage_qa":
            percentage_qa,
        "measure":
            get_measure_label(variable),
        "universe":
            universe_expression,
    })


qa_summary = pd.DataFrame(
    qa_rows
)

assert len(qa_summary) == 28

assert (
    qa_summary["percentage_qa"]
    == "PASS"
).all()

print(
    "[PASS] Table-level QA rebuilt "
    "(28/28)"
)


# ============================================================
# INDEPENDENTLY REBUILD EFFECTIVE BASES
# ============================================================

effective_base_rows = []

for _, row in plan.iterrows():

    table_id = row["table_id"]
    platform = row["platform"]
    variable = row["variable"]
    weight = row["weight"]

    universe_mask = parse_universe(
        row["universe"]
    )

    universe_data = df.loc[
        universe_mask
    ].copy()

    # TOTAL
    valid = (
        universe_data[variable].isin(
            VALID_RESPONSES
        )
        &
        universe_data[weight].notna()
    )

    total_data = universe_data.loc[
        valid
    ]

    total_n = len(total_data)

    total_neff = kish_effective_n(
        total_data[weight]
    )

    total_deff = (
        total_n / total_neff
        if (
            not pd.isna(total_neff)
            and total_neff > 0
        )
        else np.nan
    )

    effective_base_rows.append({
        "table_id": table_id,
        "platform": platform,
        "banner": "Total",
        "category": "Total",
        "unweighted_n": total_n,
        "effective_n": total_neff,
        "weighting_deff": total_deff,
    })

    # BANNERS
    for banner_var, categories in (
        banner_definitions.items()
    ):

        banner = banner_names[
            banner_var
        ]

        for code, category in (
            categories.items()
        ):

            subset = universe_data.loc[
                universe_data[
                    banner_var
                ] == code
            ]

            valid = (
                subset[variable].isin(
                    VALID_RESPONSES
                )
                &
                subset[weight].notna()
            )

            subset = subset.loc[
                valid
            ]

            n = len(subset)

            neff = kish_effective_n(
                subset[weight]
            )

            deff = (
                n / neff
                if (
                    not pd.isna(neff)
                    and neff > 0
                )
                else np.nan
            )

            effective_base_rows.append({
                "table_id": table_id,
                "platform": platform,
                "banner": banner,
                "category": category,
                "unweighted_n": n,
                "effective_n": neff,
                "weighting_deff": deff,
            })


rebuilt_bases = pd.DataFrame(
    effective_base_rows
)

assert len(rebuilt_bases) == 504

print(
    "[PASS] Effective-base matrix independently rebuilt "
    "(504/504)"
)


# ============================================================
# CROSS-CHECK STEP 04 OUTPUT
# ============================================================

base_keys = [
    "table_id",
    "platform",
    "banner",
    "category",
]

base_compare = rebuilt_bases.merge(
    generated_bases,
    on=base_keys,
    suffixes=("_qa", "_step04"),
    validate="one_to_one",
)

assert len(base_compare) == 504

assert (
    base_compare[
        "unweighted_n_qa"
    ]
    ==
    base_compare[
        "unweighted_n_step04"
    ]
).all()

for column in [
    "effective_n",
    "weighting_deff",
]:

    difference = (
        base_compare[
            f"{column}_qa"
        ]
        -
        base_compare[
            f"{column}_step04"
        ]
    ).abs()

    assert (
        difference < NUMERIC_TOLERANCE
    ).all(), (
        f"{column} differs between "
        "step 04 and final QA."
    )

print(
    "[PASS] Step 04 effective-base output "
    "independently reconciled"
)


# ============================================================
# BUILD SMALL-BASE QA
# ============================================================

small_base_rows = []

banner_only = rebuilt_bases.loc[
    rebuilt_bases["banner"]
    != "Total"
].copy()

assert len(banner_only) == 476

for _, row in banner_only.iterrows():

    displayed_base, flag = (
        classify_base(
            row["unweighted_n"]
        )
    )

    small_base_rows.append({
        "table_id":
            row["table_id"],
        "column":
            (
                f"{row['banner']} | "
                f"{row['category']}"
            ),
        "displayed_base":
            displayed_base,
        "flag":
            flag,
    })


small_base_qa = pd.DataFrame(
    small_base_rows
)

assert len(small_base_qa) == 476

print(
    "[PASS] Small-base QA rebuilt "
    "(476/476)"
)


# ============================================================
# SMALL-BASE DISTRIBUTION
# ============================================================

flag_counts = (
    small_base_qa["flag"]
    .value_counts()
    .to_dict()
)

ok_count = flag_counts.get(
    "OK",
    0,
)

small_count = flag_counts.get(
    "SMALL BASE",
    0,
)

very_small_count = flag_counts.get(
    "VERY SMALL BASE",
    0,
)

assert ok_count == 448, (
    f"Expected 448 OK cells; "
    f"found {ok_count}"
)

assert small_count == 21, (
    f"Expected 21 SMALL BASE cells; "
    f"found {small_count}"
)

assert very_small_count == 7, (
    f"Expected 7 VERY SMALL BASE cells; "
    f"found {very_small_count}"
)

print(
    "[PASS] Small-base distribution: "
    "448 OK | 21 SMALL | 7 VERY SMALL"
)


# ============================================================
# VERIFY LOW-BASE LOCATION
# ============================================================

low_base_cells = (
    banner_only.loc[
        banner_only[
            "unweighted_n"
        ] < MIN_TEST_BASE
    ]
    .copy()
)

assert len(low_base_cells) == 28, (
    f"Expected 28 low-base cells; "
    f"found {len(low_base_cells)}"
)

assert (
    low_base_cells["banner"]
    == "Gender"
).all()

assert (
    low_base_cells["category"]
    == "In some other way"
).all()

print(
    "[PASS] All 28 N < 100 cells are "
    "'Gender | In some other way'"
)


# ============================================================
# PLATFORM LOW-BASE CHECK
# ============================================================

low_base_platform = (
    low_base_cells
    .groupby("platform")
    .agg(
        tables=(
            "table_id",
            "nunique",
        ),
        min_n=(
            "unweighted_n",
            "min",
        ),
        max_n=(
            "unweighted_n",
            "max",
        ),
    )
)

expected_low_base_ranges = {
    "Facebook": (7, 35, 36),
    "Instagram": (7, 44, 44),
    "X": (7, 28, 29),
    "TikTok": (7, 32, 32),
}

for platform, (
    expected_tables,
    expected_min,
    expected_max,
) in expected_low_base_ranges.items():

    actual = low_base_platform.loc[
        platform
    ]

    assert (
        actual["tables"]
        == expected_tables
    )

    assert (
        actual["min_n"]
        == expected_min
    )

    assert (
        actual["max_n"]
        == expected_max
    )

print(
    "[PASS] Platform-specific low-base "
    "ranges validated"
)


# ============================================================
# SIGNIFICANCE QA
# ============================================================

assert len(sig_results) == 1596

assert (
    sig_results["table_id"].nunique()
    == 28
)

significant_values = (
    sig_results["significant_95"]
    .astype(str)
    .str.lower()
)

significant_count = int(
    significant_values.eq("true").sum()
)

assert significant_count == 495, (
    f"Expected 495 significant tests; "
    f"found {significant_count}"
)

sig_low_base = sig_results.loc[
    (sig_results["n_1"] < MIN_TEST_BASE)
    |
    (sig_results["n_2"] < MIN_TEST_BASE)
]

assert sig_low_base.empty, (
    "Low-base categories were used "
    "in significance testing"
)

print(
    "[PASS] Significance results validated "
    "(1,596 tests | 495 significant)"
)

print(
    "[PASS] Zero significance tests "
    "involve N < 100 categories"
)


# ============================================================
# FINAL CROSS-CHECKS
# ============================================================

assert qa_summary["table_id"].nunique() == 28
assert rebuilt_bases["table_id"].nunique() == 28
assert small_base_qa["table_id"].nunique() == 28
assert sig_results["table_id"].nunique() == 28

assert qa_summary["platform"].nunique() == 4
assert rebuilt_bases["platform"].nunique() == 4

assert qa_summary["variable"].nunique() == 28
assert qa_summary["measure"].nunique() == 7

print(
    "[PASS] Final project coverage validated"
)


# ============================================================
# EXPORT QA OUTPUTS
# ============================================================

qa_summary.to_csv(
    QA_SUMMARY_PATH,
    index=False,
    float_format="%.12g",
)

small_base_qa.to_csv(
    SMALL_BASE_PATH,
    index=False,
)

assert QA_SUMMARY_PATH.exists()
assert SMALL_BASE_PATH.exists()

print(
    "[PASS] QA summary exported to "
    "qa/qa_summary.csv"
)

print(
    "[PASS] Small-base QA exported to "
    "qa/small_base_qa.csv"
)


# ============================================================
# ROUND-TRIP OUTPUT QA
# ============================================================

saved_qa = pd.read_csv(
    QA_SUMMARY_PATH
)

saved_small = pd.read_csv(
    SMALL_BASE_PATH
)

assert len(saved_qa) == 28
assert len(saved_small) == 476

assert (
    saved_qa["percentage_qa"]
    == "PASS"
).all()

assert (
    saved_small["flag"]
    .value_counts()
    .to_dict()
    == {
        "OK": 448,
        "SMALL BASE": 21,
        "VERY SMALL BASE": 7,
    }
)

print(
    "[PASS] Exported QA files passed "
    "round-trip validation"
)


# ============================================================
# SUMMARY
# ============================================================

print("\n" + "-" * 72)
print("FINAL QA SUMMARY")
print("-" * 72)

print(
    f"Tables:                       "
    f"{len(qa_summary)}"
)

print(
    f"Percentage-QA PASS:           "
    f"{(qa_summary['percentage_qa'] == 'PASS').sum()}/28"
)

print(
    f"Effective-base records:       "
    f"{len(rebuilt_bases)}"
)

print(
    f"Banner cells reviewed:        "
    f"{len(small_base_qa)}"
)

print(
    f"Adequate bases (N >= 100):    "
    f"{ok_count}"
)

print(
    f"Small bases (30 <= N < 100):  "
    f"{small_count}"
)

print(
    f"Very small bases (N < 30):    "
    f"{very_small_count}"
)

print(
    f"Significant tests:            "
    f"{significant_count}"
)

print(
    f"Low-base significance tests:  "
    f"{len(sig_low_base)}"
)

print(
    f"Significance tests reviewed:  "
    f"{len(sig_results):,}"
)

print("\nLow-base cells by platform:")

print(
    low_base_platform
    .to_string()
)


# ============================================================
# FINAL STATUS
# ============================================================

print("\n" + "=" * 72)
print("FINAL QA PASSED AND OUTPUTS EXPORTED")
print("=" * 72)